# -*- coding: utf-8 -*-
"""Kendrick_Lang_Visuals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KVMeDrdfex-vBpvYLbJwsHp02kywDGOG
"""

from google.colab import drive
drive.mount('/content/drive')

import matplotlib.pyplot as plt
import pandas as pd

k_df = pd.read_csv('/content/drive/MyDrive/k_lang_detection_results1.csv')

len(k_df)

k_df.head()

# Count values in the 'correct?' column
accuracy_counts = k_df['langid_correct'].value_counts()

# Map short codes to full labels
labels = {
    'y': 'Correct',
    'n': 'Incorrect (Should be English)',
    'nn': 'Incorrect (Not English)'
}

# Relabel index
accuracy_counts.index = [labels.get(code, code) for code in accuracy_counts.index]

# Plot the pie chart
plt.figure(figsize=(7, 7))
plt.pie(
    accuracy_counts,
    labels=accuracy_counts.index,
    autopct='%1.1f%%',
    startangle=140,
    colors=['#A3C4DC', '#BFD8E2', '#D6E6F2']  # green, red, orange
)
plt.title("Language Detection Accuracy - langid")
plt.axis('equal')  # Ensures it's a circle
plt.show()
plt.savefig("/content/drive/MyDrive/langid_accuracy_pie_chart.png", dpi=300)

# Count values in the 'correct?' column
accuracy_counts = k_df['langdetect_correct'].value_counts()

# Map short codes to full labels
labels = {
    'y': 'Correct',
    'n': 'Incorrect (Should be English)',
    'nn': 'Incorrect (Not English)'
}

# Relabel index
accuracy_counts.index = [labels.get(code, code) for code in accuracy_counts.index]

# Plot the pie chart
plt.figure(figsize=(7, 7))
plt.pie(
    accuracy_counts,
    labels=accuracy_counts.index,
    autopct='%1.1f%%',
    startangle=140,
    colors=['#A3C4DC', '#BFD8E2', '#D6E6F2']  # green, red, orange
)
plt.title("Language Detection Accuracy - langdetect")
plt.axis('equal')  # Ensures it's a circle
plt.show()
plt.savefig("/content/drive/MyDrive/langdetect_accuracy_pie_chart.png", dpi=300)

# Count values in the 'correct?' column
accuracy_counts = k_df['lingua_correct'].value_counts()

# Map short codes to full labels
labels = {
    'y': 'Correct',
    'n': 'Incorrect (Should be English)',
    'nn': 'Incorrect (Not English)'
}

# Relabel index
accuracy_counts.index = [labels.get(code, code) for code in accuracy_counts.index]

# Plot the pie chart
plt.figure(figsize=(7, 7))
plt.pie(
    accuracy_counts,
    labels=accuracy_counts.index,
    autopct='%1.1f%%',
    startangle=140,
    colors=['#A3C4DC', '#BFD8E2', '#D6E6F2']  # green, red, orange
)
plt.title("Language Detection Accuracy - lingua")
plt.axis('equal')  # Ensures it's a circle
plt.show()
plt.savefig("/content/drive/MyDrive/lingua_accuracy_pie_chart.png", dpi=300)

plt.savefig("language_accuracy_pie_chart.png", dpi=300)